### ISSUE TITLE
proyecto de figma

### ISSUE THREAD

**Issue by carlos0716c** [SistemasTecTlaxiaco/Practica1-#1]
[PRACTICA-1.pdf](https://github.com/SistemasTecTlaxiaco/Practica1-/files/10757025/PRACTICA-1.pdf)
https://www.figma.com/proto/nUsvsUtjV2fR7aMls0MomG/Untitled?node-id=1%3A2&starting-point-node-id=1%3A2

**Comment by Luz1727** [comment]
Total: 92 de 100
calificación: 18.4% de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
